using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TripWiseJa.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddBookingsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Only create Bookings table if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'Bookings') THEN
                        CREATE TABLE ""Bookings"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""CheckInDate"" timestamp with time zone NOT NULL,
                            ""CheckOutDate"" timestamp with time zone NOT NULL,
                            ""NumberOfGuests"" integer NOT NULL,
                            ""SpecialRequests"" character varying(1000),
                            ""Status"" character varying(20) NOT NULL,
                            ""TotalPrice"" numeric(10,2),
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            ""UpdatedAt"" timestamp with time zone NOT NULL,
                            ""UserId"" integer NOT NULL,
                            ""LocationId"" integer NOT NULL,
                            CONSTRAINT ""PK_Bookings"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_Bookings_Locations_LocationId"" FOREIGN KEY (""LocationId"") REFERENCES ""Locations"" (""Id"") ON DELETE CASCADE,
                            CONSTRAINT ""FK_Bookings_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                        );
                        
                        CREATE INDEX ""IX_Bookings_LocationId"" ON ""Bookings"" (""LocationId"");
                        CREATE INDEX ""IX_Bookings_UserId"" ON ""Bookings"" (""UserId"");
                    END IF;
                END
                $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Bookings");
        }
    }
}
